version: "3.0"

services:
  webserver:
    image: nginx
    container_name: laravel_nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/data/logs/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on: 
      - mysql
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: laravel_php-fpm
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: juneyai-dev
      MYSQL_USER: hbich
      MYSQL_PASSWORD: bichht
      MYSQL_ROOT_PASSWORD: bichht

  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: laravel_workspace
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    tty: true

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
